# Generated by Django 6.0.5 on 2026-05-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttransaction_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='verification_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Kode Verifikasi'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='image',
            field=models.FileField(blank=True, help_text='Format: JPG, PNG, PDF', null=True, upload_to='bukti_pembayaran/'),
        ),
    ]
