# Generated by Django 6.0.5 on 2026-05-24 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_assigned_level_internalinfo'),
        ('payments', '0003_paymenttransaction_verification_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlastEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('spp', 'SPP'), ('kegiatan', 'Uang Kegiatan'), ('eca', 'ECA'), ('cambridge', 'Cambridge Assessment')], max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blast_emails', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Blast Email Log',
                'verbose_name_plural': 'Blast Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
