# Generated by Django 6.0.5 on 2026-05-24 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_blastemaillog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blastemaillog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blastemaillog',
            name='payment_type',
            field=models.CharField(choices=[('spp', 'SPP'), ('kegiatan', 'Uang Kegiatan'), ('eca', 'ECA'), ('cambridge', 'Cambridge Assessment'), ('seragam', 'Pembayaran Seragam'), ('denda', 'Pembayaran Denda')], max_length=20),
        ),
        migrations.CreateModel(
            name='BlastEmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Template')),
                ('payment_type', models.CharField(choices=[('spp', 'SPP'), ('kegiatan', 'Uang Kegiatan'), ('eca', 'ECA'), ('cambridge', 'Cambridge Assessment'), ('seragam', 'Pembayaran Seragam'), ('denda', 'Pembayaran Denda')], max_length=20, verbose_name='Jenis Pembayaran')),
                ('subject', models.CharField(max_length=300, verbose_name='Subjek Email')),
                ('body', models.TextField(verbose_name='Body Email')),
                ('bank_account', models.CharField(blank=True, max_length=200, verbose_name='Rekening Tujuan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template Blast Email',
                'verbose_name_plural': 'Template Blast Email',
                'ordering': ['-updated_at'],
            },
        ),
    ]
