# Generated by Django 6.0.5 on 2026-05-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_blastemaillog_read_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blastemailtemplate',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Template Default'),
        ),
    ]
