# Generated by Django 6.0.5 on 2026-05-23 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(verbose_name='Deskripsi kegiatan')),
                ('start_date', models.DateField(verbose_name='Tanggal mulai')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tanggal selesai')),
                ('cover_image', models.ImageField(blank=True, upload_to='kegiatan/')),
                ('google_drive_link1', models.URLField(blank=True, verbose_name='Link Google Drive 1')),
                ('google_drive_link2', models.URLField(blank=True, verbose_name='Link Google Drive 2')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Nomor bukti/invoice')),
                ('signature_data', models.TextField(blank=True, help_text='Data tanda tangan canvas (base64) - dari PIC')),
                ('reflection', models.TextField(blank=True, verbose_name='Refleksi')),
                ('evaluation', models.TextField(blank=True, verbose_name='Evaluasi')),
                ('budget_real', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Budget Realisasi')),
                ('pic_notes', models.TextField(blank=True, verbose_name='Catatan PIC')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan ke PIC'), ('pic_approved', 'Disetujui PIC'), ('approved', 'Disetujui'), ('revised', 'Revisi'), ('rejected', 'Ditolak')], default='draft', max_length=20)),
                ('rejection_notes', models.TextField(blank=True, help_text='Catatan revisi/penolakan')),
                ('pic_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('pic_signature_data', models.TextField(blank=True, help_text='Tanda tangan PIC (base64)')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_reports', to='accounts.academicyear')),
                ('pic', models.ForeignKey(limit_choices_to={'role': 'pic_teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='activity_reports', to=settings.AUTH_USER_MODEL)),
                ('pic_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pic_reviewed_activities', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laporan Kegiatan',
                'verbose_name_plural': 'Laporan Kegiatan',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityIncomeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Pemasukan'), ('expense', 'Pengeluaran')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('date', models.DateField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='activities.activityreport')),
            ],
            options={
                'verbose_name': 'Transaksi Kegiatan',
                'verbose_name_plural': 'Transaksi Kegiatan',
            },
        ),
        migrations.CreateModel(
            name='ActivityEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='laporan/', verbose_name='File bukti')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='activities.activityreport')),
            ],
            options={
                'verbose_name': 'Bukti Laporan',
                'verbose_name_plural': 'Bukti Laporan',
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Kegiatan')),
                ('objectives', models.TextField(verbose_name='Objectives/Goal')),
                ('values_knowledge', models.TextField(blank=True, verbose_name='Value Knowledge')),
                ('values_faith', models.TextField(blank=True, verbose_name='Value Faith')),
                ('values_character', models.TextField(blank=True, verbose_name='Value Character')),
                ('budget', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Budget')),
                ('month', models.CharField(help_text='Bulan pelaksanaan', max_length=20, verbose_name='Bulan')),
                ('time_start', models.DateField(verbose_name='Time Start')),
                ('time_finish', models.DateField(verbose_name='Time Finish')),
                ('pic', models.CharField(blank=True, max_length=200, verbose_name='PIC')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_types_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jenis Kegiatan',
                'verbose_name_plural': 'Jenis Kegiatan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activityreport',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='activities.activitytype', verbose_name='Jenis Kegiatan'),
        ),
    ]
