# Generated by Django 6.0.5 on 2026-05-25 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activityreport',
            name='feedback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='feedback_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_feedback_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='feedback_notes',
            field=models.TextField(blank=True, help_text='Catatan/feedback dari Kepsek / VP Activity'),
        ),
        migrations.AddField(
            model_name='activityreport',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL slug auto-generated from title', max_length=255),
        ),
    ]
