# Generated by Django 6.0.5 on 2026-05-23 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambridgeFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('checkpoints', 'Checkpoints'), ('igcse', 'IGCSE'), ('as_level', 'AS Level'), ('a_level', 'A Level')], max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarif Cambridge',
                'verbose_name_plural': 'Tarif Cambridge',
            },
        ),
        migrations.CreateModel(
            name='CambridgeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('checkpoints', 'Checkpoints'), ('igcse', 'IGCSE'), ('as_level', 'AS Level'), ('a_level', 'A Level')], max_length=20)),
                ('subject', models.CharField(max_length=100, verbose_name='Mata Pelajaran')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambridge_payments', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Cambridge Assessment',
                'verbose_name_plural': 'Cambridge Assessment',
            },
        ),
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_type', models.CharField(choices=[('spp', 'SPP'), ('dpp', 'DPP'), ('eca', 'ECA'), ('kegiatan', 'Uang Kegiatan'), ('other', 'Lainnya')], max_length=20)),
                ('description', models.TextField()),
                ('original_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('comp_amount', models.DecimalField(decimal_places=0, help_text='Jumlah kompensasi/potongan', max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=0, editable=False, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_compensations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compensations', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Kompensasi Pembayaran',
                'verbose_name_plural': 'Kompensasi Pembayaran',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('spp', 'SPP'), ('dpp', 'DPP'), ('eca', 'ECA'), ('kegiatan', 'Uang Kegiatan')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, help_text='Jumlah diskon dalam Rupiah', max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discounts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Diskon',
                'verbose_name_plural': 'Diskon',
            },
        ),
        migrations.CreateModel(
            name='DPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pembangunan', 'DPP Pembangunan'), ('kegiatan', 'Uang Kegiatan')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Disetujui'), ('revised', 'Revisi'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='dpp_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpp_payments', to='accounts.student')),
            ],
            options={
                'verbose_name': 'DPP Payment',
                'verbose_name_plural': 'DPP Payments',
            },
        ),
        migrations.CreateModel(
            name='DPPReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pembangunan', 'DPP Pembangunan'), ('kegiatan', 'Uang Kegiatan')], max_length=20)),
                ('total_students', models.IntegerField(default=0)),
                ('total_paid', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total_collected', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan'), ('approved', 'Disetujui'), ('revised', 'Revisi'), ('rejected', 'Ditolak')], default='draft', max_length=20)),
                ('rejection_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpp_reports', to='accounts.academicyear')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpp_reports', to='accounts.grade')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_dpp_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laporan DPP',
                'verbose_name_plural': 'Laporan DPP',
            },
        ),
        migrations.CreateModel(
            name='SPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spp_rates', to='accounts.academicyear')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spp_rates', to='accounts.grade')),
            ],
            options={
                'verbose_name': 'SPP Rate',
                'verbose_name_plural': 'SPP Rates',
                'unique_together': {('academic_year', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='SPPBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')])),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('virtual_account', models.CharField(blank=True, max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('spp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='finance.spp')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spp_bills', to='accounts.student')),
            ],
            options={
                'verbose_name': 'SPP Bill',
                'verbose_name_plural': 'SPP Bills',
                'unique_together': {('student', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.IntegerField(choices=[(1, 'Peringatan Pertama'), (2, 'Peringatan Kedua'), (3, 'Peringatan Ketiga')])),
                ('month', models.IntegerField(blank=True, choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')], null=True)),
                ('notes', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='accounts.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='accounts.student')),
                ('spp_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='finance.sppbill')),
            ],
            options={
                'verbose_name': 'Payment Reminder',
                'verbose_name_plural': 'Payment Reminders',
            },
        ),
        migrations.CreateModel(
            name='SPPReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'Januari'), (2, 'Februari'), (3, 'Maret'), (4, 'April'), (5, 'Mei'), (6, 'Juni'), (7, 'Juli'), (8, 'Agustus'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Desember')])),
                ('year', models.IntegerField()),
                ('total_bills', models.IntegerField(default=0)),
                ('total_paid', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('total_collected', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan'), ('approved', 'Disetujui'), ('revised', 'Revisi'), ('rejected', 'Ditolak')], default='draft', max_length=20)),
                ('rejection_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spp_reports', to='accounts.academicyear')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spp_reports', to='accounts.grade')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_spp_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laporan Bulanan SPP',
                'verbose_name_plural': 'Laporan Bulanan SPP',
            },
        ),
    ]
