# Generated by Django 6.0.5 on 2026-05-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambridgefee',
            name='subject',
            field=models.CharField(default='All', max_length=100, verbose_name='Mata Pelajaran'),
        ),
        migrations.AlterField(
            model_name='cambridgefee',
            name='exam_type',
            field=models.CharField(choices=[('checkpoints', 'Checkpoints'), ('igcse', 'IGCSE'), ('as_level', 'AS Level'), ('a_level', 'A Level')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cambridgefee',
            unique_together={('exam_type', 'subject')},
        ),
    ]
