# Generated by Django 6.0.5 on 2026-05-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_cambridgefee_subject_alter_cambridgefee_exam_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compensation',
            name='discount_method',
            field=models.CharField(choices=[('nominal', 'Nominal (Rp)'), ('persen', 'Persen (%)')], default='nominal', max_length=10),
        ),
        migrations.AlterField(
            model_name='compensation',
            name='comp_amount',
            field=models.DecimalField(decimal_places=0, help_text='Jumlah kompensasi/potongan (Rp atau %)', max_digits=12),
        ),
    ]
