# Generated by Django 6.0.5 on 2026-05-25 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_compensation_discount_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA')], max_length=10, unique=True)),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nama Bank')),
                ('account_number', models.CharField(max_length=50, verbose_name='No. Rekening')),
                ('account_holder', models.CharField(max_length=200, verbose_name='Atas Nama')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rekening Bank',
                'verbose_name_plural': 'Rekening Bank',
                'ordering': ['level'],
            },
        ),
    ]
