# Generated by Django 6.0.5 on 2026-05-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sppbill',
            name='verification_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kode Verifikasi'),
        ),
    ]
