# Generated by Django 6.0.5 on 2026-05-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_bankaccount_approved_at_bankaccount_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['level', 'payment_type'], 'verbose_name': 'Rekening Bank', 'verbose_name_plural': 'Rekening Bank'},
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='payment_type',
            field=models.CharField(choices=[('spp', 'SPP'), ('dpp_pembangunan', 'DPP Pembangunan'), ('uang_kegiatan', 'Uang Kegiatan'), ('cambridge', 'Cambridge Assessment')], default='spp', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='level',
            field=models.CharField(choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('level', 'payment_type')},
        ),
    ]
