# Generated by Django 6.0.5 on 2026-05-23 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assigned_level',
            field=models.CharField(blank=True, choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA'), ('sd_smp', 'SD & SMP'), ('smp_sma', 'SMP & SMA'), ('sd_smp_sma', 'SD, SMP & SMA')], help_text='Jenjang akses untuk Kepsek / VP Activity / TU', max_length=10),
        ),
        migrations.CreateModel(
            name='InternalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('level', models.CharField(choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA'), ('all', 'Semua Jenjang')], default='all', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='internal_info/')),
                ('is_published', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_info', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informasi Internal',
                'verbose_name_plural': 'Informasi Internal',
                'ordering': ['-created_at'],
            },
        ),
    ]
