# Generated by Django 6.0.5 on 2026-05-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_assigned_level_internalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalinfo',
            name='google_drive_link',
            field=models.URLField(blank=True, verbose_name='Tautan Google Drive'),
        ),
        migrations.AlterField(
            model_name='internalinfo',
            name='level',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
