# Generated by Django 6.0.5 on 2026-05-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_internalinfo_google_drive_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_phone',
            field=models.BooleanField(default=False, verbose_name='Tampilkan nomor HP di profil'),
        ),
    ]
