# Generated by Django 6.0.5 on 2026-05-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_show_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classgrade',
            unique_together={('name', 'grade', 'academic_year')},
        ),
    ]
