# Generated by Django 6.0.5 on 2026-05-23 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA')], max_length=10, verbose_name='Jenjang')),
                ('title', models.CharField(max_length=200, verbose_name='Judul (mis: Kurikulum Merdeka)')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('subjects', models.TextField(blank=True, help_text='Daftar mata pelajaran (dipisah koma)')),
                ('pedagogical', models.TextField(blank=True, verbose_name='Pendekatan Pedagogis')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Informasi Kurikulum',
                'verbose_name_plural': 'Informasi Kurikulum',
                'ordering': ['level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='GradingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA')], max_length=10, verbose_name='Jenjang')),
                ('title', models.CharField(max_length=200, verbose_name='Judul')),
                ('description', models.TextField(verbose_name='Penjelasan Sistem Penilaian')),
                ('grading_scale', models.TextField(blank=True, help_text='Skala nilai (A/B/C/dll)')),
                ('report_guide', models.TextField(blank=True, verbose_name='Panduan Interpretasi Rapor')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sistem Penilaian',
                'verbose_name_plural': 'Sistem Penilaian',
                'ordering': ['level', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Sekolah')),
                ('address', models.TextField(verbose_name='Alamat Lengkap')),
                ('phone', models.CharField(max_length=50, verbose_name='Nomor Telepon')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Resmi')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('vision', models.TextField(verbose_name='Visi')),
                ('mission', models.TextField(verbose_name='Misi')),
                ('core_values', models.TextField(blank=True, verbose_name='Nilai-nilai Inti')),
                ('history', models.TextField(blank=True, verbose_name='Sejarah Singkat')),
                ('accreditation', models.CharField(blank=True, max_length=100, verbose_name='Akreditasi')),
                ('logo', models.ImageField(blank=True, upload_to='school/', verbose_name='Logo Sekolah')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil Sekolah',
                'verbose_name_plural': 'Profil Sekolah',
            },
        ),
        migrations.CreateModel(
            name='SpecialProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nama Program Khusus')),
                ('description', models.TextField(verbose_name='Deskripsi')),
                ('target_level', models.CharField(blank=True, help_text='Target jenjang', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Program Khusus',
                'verbose_name_plural': 'Program Khusus',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nama Lengkap')),
                ('photo', models.ImageField(blank=True, upload_to='teachers/')),
                ('qualification', models.CharField(max_length=200, verbose_name='Kualifikasi Pendidikan')),
                ('subjects', models.CharField(max_length=300, verbose_name='Mata Pelajaran Diampu')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Jabatan')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Profesional')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Kontak')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profil Guru',
                'verbose_name_plural': 'Profil Guru',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Label (mis: Administrasi, Darurat)')),
                ('contact_type', models.CharField(choices=[('phone', 'Telepon'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('value', models.CharField(max_length=200)),
                ('is_emergency', models.BooleanField(default=False, verbose_name='Kontak Darurat')),
                ('order', models.IntegerField(default=0)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='public_info.schoolprofile')),
            ],
            options={
                'verbose_name': 'Kontak',
                'verbose_name_plural': 'Kontak',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50, verbose_name='Platform (Instagram, YouTube, dll)')),
                ('url', models.URLField()),
                ('icon', models.CharField(blank=True, help_text='Nama ikon FontAwesome', max_length=50)),
                ('school', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='public_info.schoolprofile')),
            ],
            options={
                'verbose_name': 'Media Sosial',
                'verbose_name_plural': 'Media Sosial',
            },
        ),
    ]
