# Generated by Django 6.0.5 on 2026-05-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolLevelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA')], max_length=10, unique=True, verbose_name='Jenjang')),
                ('accreditation', models.CharField(blank=True, max_length=100, verbose_name='Akreditasi')),
                ('accreditation_link', models.URLField(blank=True, verbose_name='Link Akreditasi')),
                ('accreditation_valid_from', models.DateField(blank=True, null=True, verbose_name='Akreditasi Berlaku Dari')),
                ('izin_operasional', models.CharField(blank=True, max_length=200, verbose_name='Izin Operasional')),
                ('izin_valid_from', models.DateField(blank=True, null=True, verbose_name='Izin Operasional Berlaku Dari')),
            ],
            options={
                'verbose_name': 'Informasi Jenjang',
                'verbose_name_plural': 'Informasi Jenjang',
            },
        ),
        migrations.CreateModel(
            name='TeacherStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA')], max_length=10, unique=True, verbose_name='Jenjang')),
                ('image', models.ImageField(upload_to='structures/', verbose_name='Gambar Struktur Organisasi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Struktur Guru',
                'verbose_name_plural': 'Struktur Guru',
            },
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('sd', 'SD'), ('smp', 'SMP'), ('sma', 'SMA')], max_length=10, verbose_name='Jenjang'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='nip',
            field=models.CharField(blank=True, max_length=50, verbose_name='NIP'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='teachers/', verbose_name='Foto'),
        ),
    ]
