# Generated by Django 6.0.5 on 2026-05-23 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECASetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_selection', models.IntegerField(default=3, help_text='Maksimal jumlah ECA yang bisa dipilih per siswa')),
            ],
            options={
                'verbose_name': 'Pengaturan ECA',
                'verbose_name_plural': 'Pengaturan ECA',
            },
        ),
        migrations.CreateModel(
            name='ECAType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ECA Type',
                'verbose_name_plural': 'ECA Types',
            },
        ),
        migrations.CreateModel(
            name='ECAProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('duration', models.CharField(choices=[('1month', '1 Bulan'), ('3months', '3 Bulan'), ('6months', '6 Bulan'), ('1year', '1 Tahun')], max_length=20)),
                ('max_participants', models.IntegerField(default=0)),
                ('is_open', models.BooleanField(default=True)),
                ('schedule', models.TextField(blank=True, help_text='Jadwal kegiatan 1')),
                ('schedule2', models.TextField(blank=True, help_text='Jadwal kegiatan 2')),
                ('pic', models.CharField(blank=True, help_text='Penanggung jawab', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eca_programs', to='accounts.academicyear')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eca_programs', to='accounts.grade')),
                ('eca_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='eca.ecatype')),
            ],
            options={
                'verbose_name': 'ECA Program',
                'verbose_name_plural': 'ECA Programs',
            },
        ),
        migrations.CreateModel(
            name='ECARegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='eca.ecaprogram')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eca_registrations', to='accounts.student')),
            ],
            options={
                'verbose_name': 'ECA Registration',
                'verbose_name_plural': 'ECA Registrations',
                'unique_together': {('student', 'program')},
            },
        ),
        migrations.CreateModel(
            name='ECAPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, help_text='Jumlah yang dibayarkan', max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Diterima'), ('revised', 'Revisi'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('payment_notes', models.TextField(blank=True, help_text='Catatan review pembayaran')),
                ('under_over_amount', models.DecimalField(decimal_places=0, default=0, help_text='Kelebihan (+) / Kekurangan (-)', max_digits=12)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eca_payment_reviews', to=settings.AUTH_USER_MODEL)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='eca.ecaregistration')),
            ],
        ),
        migrations.CreateModel(
            name='ECAInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('pdf', models.FileField(blank=True, upload_to='eca_invoices/')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eca_invoices', to='accounts.student')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='eca.ecaregistration')),
            ],
            options={
                'verbose_name': 'ECA Invoice',
                'verbose_name_plural': 'ECA Invoices',
            },
        ),
        migrations.CreateModel(
            name='ECAReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('monthly', 'Bulanan'), ('semester', 'Semester'), ('final', 'Akhir Tahun')], max_length=20)),
                ('total_students', models.IntegerField(default=0)),
                ('total_paid', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Diajukan'), ('approved', 'Disetujui'), ('revised', 'Revisi'), ('rejected', 'Ditolak')], default='draft', max_length=20)),
                ('rejection_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eca_reports', to='accounts.academicyear')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='eca.ecaprogram')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_eca_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Laporan ECA',
                'verbose_name_plural': 'Laporan ECA',
            },
        ),
        migrations.CreateModel(
            name='ECAScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Keterangan')),
                ('scored_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='eca.ecaprogram')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eca_scores', to='accounts.student')),
            ],
            options={
                'verbose_name': 'ECA Score',
                'verbose_name_plural': 'ECA Scores',
                'unique_together': {('student', 'program')},
            },
        ),
    ]
