# Generated by Django 6.0.5 on 2026-05-24 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eca', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ecaprogram',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_eca_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ecaprogram',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Disetujui Director'),
        ),
        migrations.AddField(
            model_name='ecaregistration',
            name='rejection_notes',
            field=models.TextField(blank=True, verbose_name='Catatan Penolakan'),
        ),
        migrations.AddField(
            model_name='ecaregistration',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecaregistration',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_eca_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
