# Generated by Django 6.0.5 on 2026-05-25 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eca', '0002_ecaprogram_approved_by_ecaprogram_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecaprogram',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Informasi penting lainnya'),
        ),
        migrations.AddField(
            model_name='ecaprogram',
            name='coach_profile',
            field=models.TextField(blank=True, help_text='Profil pelatih / instruktur'),
        ),
        migrations.AddField(
            model_name='ecaprogram',
            name='location',
            field=models.CharField(blank=True, help_text='Lokasi kegiatan', max_length=200),
        ),
        migrations.AddField(
            model_name='ecaprogram',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Link Google Meet / Zoom jika online'),
        ),
        migrations.AddField(
            model_name='ecaprogram',
            name='rules',
            field=models.TextField(blank=True, help_text='Ketentuan dan tata tertib'),
        ),
        migrations.AlterField(
            model_name='ecaprogram',
            name='schedule',
            field=models.TextField(blank=True, help_text='Jadwal kegiatan rutin'),
        ),
        migrations.AlterField(
            model_name='ecaprogram',
            name='schedule2',
            field=models.TextField(blank=True, help_text='Jadwal kegiatan tambahan'),
        ),
    ]
